name: needsfine_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 지도 패키지
  flutter_naver_map: ^1.2.3
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  permission_handler: ^11.3.1

  # UI & 유틸리티
  carousel_slider: ^5.0.0
  shared_preferences: ^2.2.3
  http: ^1.2.1
  scrollable_positioned_list: ^0.3.8
  image_picker: ^1.0.0
  intl: ^0.18.1
  unorm_dart: ^0.2.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon.png # [수정] 올바른 파일만 남김
