name: needsfine_app
description: "A new Flutter project for NeedsFine app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Supabase
  supabase_flutter: ^2.5.2

  # Maps & Location
  flutter_naver_map: ^1.4.4
  geolocator: ^11.0.0
  geocoding: ^3.0.0

  # Utils & UI
  permission_handler: ^11.3.1
  carousel_slider: ^5.0.0
  shared_preferences: ^2.2.3
  http: ^1.6.0
  scrollable_positioned_list: ^0.3.8
  image_picker: ^1.1.2
  intl: ^0.20.2
  unorm_dart: ^0.2.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  uuid: ^4.1.0
  url_launcher: ^6.1.12

  # Auth
  kakao_flutter_sdk: ^1.9.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon.png
    - assets/kakao_logo.png
    - assets/google_g_logo.png
    - assets/naver_login.png